name: Build and Release JARs

on:
  pull_request:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build Client JAR
        run: |
          
          javac --module-path /YourPathToTheJFX/javafx-sdk/javafx-sdk-21.0.2/lib --add-modules javafx.controls,javafx.fxml -d jar/ClientApp src/main/java/client/*.java src/main/java/resources/*.java

          echo "Main-Class: client.ClientApp" > jar/manifest.txt
          jar cfe jar/ClientApp.jar client.ClientApp -C jar/ClientApp .

      - name: Build Server JAR
        run: |

          javac --module-path /YourPathToTheJFX/javafx-sdk/javafx-sdk-21.0.2/lib --add-modules javafx.controls,javafx.fxml -d jar/ServerApp src/main/java/client/*.java src/main/java/resources/*.java src/main/java/server/*.java
          echo "Main-Class: server.ServerApp" > jar/manifest.txt
          jar cfe jar/ServerApp.jar server.ServerApp -C jar/ServerApp .


      - name: List JAR contents
        run: ls -R jar

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: JAR-Release
          path: jar
